version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    groups:
      compatible-updates:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: America/New_York
    open-pull-requests-limit: 5
